Write database schema for counter
Resume-Tracker/Portfolio-Tracker pull request #1
Opened 2020-10-21 07:51 UTC by jmun10

2020-10-21 18:16 UTC, michardy requested changes
Please fix the database path and add the nullability of company.  It appears nullability might default to true but the ambiguity is a problem.

2020-10-21 18:16 UTC, michardy commented on app/db.py
> +    company = Column(String(50))
Please add the attribute `nullable=True`

2020-10-21 18:16 UTC, michardy commented on app/db.py
> +engine = create_engine('sqlite:///database.db', echo=True)
The database path will either need to be made relative on both Windows and Linux, docker will need to be used, or a remote database will have to be set up.

2020-10-21 18:56 UTC, michardy commented on app/db.py
> +engine = create_engine('sqlite:///database.db', echo=True)
So it appears that specifically with SQLAlchemy this is a relative path.  This does not need to be changed.

2020-10-23 16:12 UTC, michardy approved these changes

2020-10-23 18:08 UTC, michardy commented
I am realizing we might want to use a [`DateTime`](https://docs.sqlalchemy.org/en/13/core/type_basics.html#sqlalchemy.types.DateTime) object for timestamp.

2020-10-23 18:39 UTC, hyunjoon99 approved these changes

2020-10-23 18:57 UTC, merged