PT-28: added table that shows company name and view count
Resume-Tracker/Portfolio-Tracker pull request #13
Opened 2020-11-09 19:58 UTC by hli086

2020-11-10 19:08 UTC, michardy approved these changes

2020-11-13 17:09 UTC, hli086 commented
I still need to modularize the code but this will work for now

2020-11-13 22:27 UTC, timle3 requested changes
update the README.md to match the one we have right now. Also ignore the public folder since we don't need it. After that's done I can approve the request.

2020-11-13 23:11 UTC, timle3 approved these changes

2020-11-13 23:11 UTC, merged